### ISSUE TITLE
Confirm more details about to be published

### ISSUE THREAD

**Issue by rprieto** [thlorenz/irish-pub#1]
Such a handy tool, thanks!
What do you think about also printing a few more things as a confirmation?
- the version number from `package.json`
- the current npm user from `npm whoami`

```
npm publish will create version 1.0.3 as rprieto
and include the following files:
```

**Comment by thlorenz** [comment]
I'm open to that, would you please submit a PR?

**Comment by rprieto** [comment]
No problem. Do you have a preference between:
- another small utility called from the binary

``` js
metadata.read(function(err, data) {
  if (err) return console.error(err);  
  console.log(/* message with the metadata */);
  irishPub(process.cwd()).pipe(process.stdout);
});
```
- or extending the `irishPub` stream to emit a `metadata` event

``` js
irishPub(process.cwd())
.on('metadata', function(meta) { console.log(/* message with the metadata */); })
.on('error', function (err) { console.error(err) })
.pipe(process.stdout)
```

**Comment by thlorenz** [comment]
No big preference if results are the same.
Just submit a PR and we discuss from there.
Thanks.
