### ISSUE TITLE
Working with private NPM servers?

### ISSUE THREAD

**Issue by grofit** [thlorenz/irish-pub#13]
We have a private NPM server setup on the local network, (I think its Sinopia/Vedaccio) however if I try and do an `irish-pub` on a package which goes to this private npm server I just get the error:

```
Cannot get current npm user
```

As the server is only on the local network and is not exposed externally it allows anonymous publishing so there are no users associated with it, and we just include in our `package.json` files:

```
"publishConfig": {
    "scope": "@ourPrivateScope",
    "registry": "http://our-npm-server/"
  }
```

Not sure if this is a bug or intended output, as it doesnt mention that you support anon/private npm repos, so just wanted to check.

**Comment by chinesedfan** [comment]
This package should be able to work with private NPM servers. You were failed when executing `npm whoami`. Please make sure you have logged in before running `irish-pub`.
