### ISSUE TITLE
irish-pub invokes prepublish script and fails

### ISSUE THREAD

**Issue by eush77** [thlorenz/irish-pub#2]
Consider this `package.json`:

``` json
{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "prepublish": "echo prepublished"
  }
}
```

`irish-pub` should not `npm pack` to obtain the list of files as it will run `prepublish`.

```
$ irish-pub
npm publish will include the following files:

{ [Error: ENOENT, open '/tmp/example/> example@0.0.0 prepublish /tmp/example
> echo prepublished

prepublished
example-0.0.0.tgz']
  errno: 34,
  code: 'ENOENT',
  path: '/tmp/example/> example@0.0.0 prepublish /tmp/example\n> echo prepublished\n\nprepublished\nexample-0.0.0.tgz' }
```

**Comment by ljharb** [comment]
I'm running into this problem as well.

However, I think the prepublish script _should_ be run, since the whole point of those is to create compiled files for distribution on npm.

**Comment by ljharb** [comment]
This seems to be because `npm install` runs `prepublish` for some reason (thanks coffeescript) - https://github.com/npm/npm/issues/6887 discusses a plan to fix it. I suspect that will fix `irish-pub` also.

**Comment by thlorenz** [comment]
> should not `npm pack`

This is how it obtains the information it needs.

Cannot fix here, sorry, let's hope npm fixes that as @ljharb pointed out.

Closing issue for now, but open for a PR that fixes this here (if possible) without huge changes to how things work.
