### ISSUE TITLE
Fails with in-publish

### ISSUE THREAD

**Issue by joeybaker** [thlorenz/irish-pub#7]
When using irish-pub with https://github.com/iarna/in-publish, irish-pub fails with `Error: ENOENT: no such file or directory`

example package.json

``` json
    "prepublish": "in-publish && echo hi || not-in-publish",
```

**Comment by vweevers** [comment]
Prepublish output is now accounted for (#5), which I think is the issue here too. Does the master branch fix it for you? Please try:

```
$ npm i thlorenz/irish-pub -g
$ irish-pub
```

**Comment by joeybaker** [comment]
Confirmed. Works great. Thanks!
